from collections import deque
from sched import scheduler
from typing import Pattern

import minqlx

_re_say: Pattern
_re_say_team: Pattern
_re_callvote: Pattern
_re_vote: Pattern
_re_team: Pattern
_re_vote_ended: Pattern
_re_userinfo: Pattern

frame_tasks: scheduler
next_frame_tasks: deque

_zmq_warning_issued: bool
_first_game: bool
_ad_round_number: int

_print_redirection: minqlx.AbstractChannel | None
_print_buffer: str


def handle_rcon(cmd: str): ...
def handle_client_command(client_id: int, cmd: str): ...
def handle_server_command(client_id: int, cmd: str): ...
def handle_frame(): ...
def handle_new_game(is_restart: bool): ...
def handle_set_configstring(index: int, value: str): ...
def handle_player_connect(client_id: int, _is_bot: bool): ...
def handle_player_loaded(client_id: int): ...
def handle_player_disconnect(client_id: int, reason: str | None): ...
def handle_player_spawn(client_id: int): ...
def handle_kamikaze_use(client_id: int): ...
def handle_kamikaze_explode(client_id: int, is_used_on_demand: bool): ...
def handle_console_print(text: str | None): ...
def redirect_print(channel: minqlx.AbstractChannel): ...
def register_handlers() -> None: ...
