from typing import TYPE_CHECKING

if TYPE_CHECKING:
    # noinspection PyPackageRequirements
    from discord import Interaction, Member

    # noinspection PyPackageRequirements
    from discord.ext.commands import Bot

async def slap(interaction: Interaction, member: Member) -> None: ...
async def _slap(interaction: Interaction, member: Member) -> None: ...
def int_set(string_set: set[str] | None) -> set[int]: ...
async def send_to_discord_and_quake(interaction: Interaction, message: str) -> None: ...
async def setup(bot: Bot) -> None: ...
