# noinspection PyPackageRequirements
from discord import Interaction

# noinspection PyPackageRequirements
from discord.ext.commands import Bot, Cog, Context

from minqlx import Game, Player

def get_game_info(game: Game) -> str: ...
def player_data() -> str: ...
def team_data(player_list: list[Player]) -> str: ...
def game_status_with_teams() -> str: ...
def int_set(string_set: set[str] | None) -> set[int]: ...

class Status(Cog):
    bot: Bot
    discord_trigger_status: str
    discord_triggered_channel_message_prefix: str
    discord_relay_channel_ids: set[int]
    discord_triggered_channel_ids: set[int]
    def __init__(self, bot: Bot) -> None: ...
    def is_message_in_relay_or_triggered_channel(self, ctx: Context) -> bool: ...
    async def trigger_status(self, ctx: Context, *_args, **_kwargs) -> None: ...
    async def slash_trigger_status(self, interaction: Interaction) -> None: ...
    def is_message_in_triggered_channel(self, ctx: Context) -> bool: ...

async def setup(bot: Bot): ...
