from typing import TYPE_CHECKING
# noinspection PyPackageRequirements
from discord.ext.commands import Bot, Cog

if TYPE_CHECKING:
    from minqlx import Game

def get_game_info(game: Game) -> str: ...
def game_status_information(game: Game) -> str: ...
def int_set(string_set: set[str] | None) -> set[int]: ...

class TopicUpdater(Cog):
    bot: Bot
    discord_relay_channel_ids: set[int]
    discord_triggered_channel_ids: set[int]
    discord_update_triggered_channels_topic: bool
    discord_topic_update_interval: int
    discord_kept_topic_suffixes: dict[int, str]
    def __init__(self, bot: Bot) -> None: ...
    async def cog_load(self) -> None: ...
    def _topic_updater(self) -> None: ...
    def update_topics_on_relay_and_triggered_channels(self, topic: str) -> None: ...
    def set_topic_on_discord_channels(self, channel_ids: set[int], topic: str) -> None: ...
    def is_discord_logged_in(self) -> bool: ...
    def update_topic_on_channels_and_keep_channel_suffix(self, channel_ids: set[int], topic: str) -> None: ...

async def setup(bot: Bot) -> None: ...
