name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Run coverage with tox
      run: tox -r -e coverage
    - name: Upload coverage.xml
      uses: actions/upload-artifact@v3
      with:
        name: tox-gh-actions-coverage
        path: coverage.xml
        if-no-files-found: error
    - name: Upload coverage.xml to codecov
      uses: codecov/codecov-action@v2
